// Generated by gencpp from file esw/MotorCommand.msg
// DO NOT EDIT!


#ifndef ESW_MESSAGE_MOTORCOMMAND_H
#define ESW_MESSAGE_MOTORCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace esw
{
template <class ContainerAllocator>
struct MotorCommand_
{
  typedef MotorCommand_<ContainerAllocator> Type;

  MotorCommand_()
    : motor1_speed(0.0)
    , motor2_speed(0.0)  {
    }
  MotorCommand_(const ContainerAllocator& _alloc)
    : motor1_speed(0.0)
    , motor2_speed(0.0)  {
  (void)_alloc;
    }



   typedef float _motor1_speed_type;
  _motor1_speed_type motor1_speed;

   typedef float _motor2_speed_type;
  _motor2_speed_type motor2_speed;





  typedef boost::shared_ptr< ::esw::MotorCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::esw::MotorCommand_<ContainerAllocator> const> ConstPtr;

}; // struct MotorCommand_

typedef ::esw::MotorCommand_<std::allocator<void> > MotorCommand;

typedef boost::shared_ptr< ::esw::MotorCommand > MotorCommandPtr;
typedef boost::shared_ptr< ::esw::MotorCommand const> MotorCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::esw::MotorCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::esw::MotorCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::esw::MotorCommand_<ContainerAllocator1> & lhs, const ::esw::MotorCommand_<ContainerAllocator2> & rhs)
{
  return lhs.motor1_speed == rhs.motor1_speed &&
    lhs.motor2_speed == rhs.motor2_speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::esw::MotorCommand_<ContainerAllocator1> & lhs, const ::esw::MotorCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace esw

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::esw::MotorCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::esw::MotorCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::esw::MotorCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::esw::MotorCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::esw::MotorCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::esw::MotorCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::esw::MotorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "44cbd85de4c6dd4929217d06c0fc9617";
  }

  static const char* value(const ::esw::MotorCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x44cbd85de4c6dd49ULL;
  static const uint64_t static_value2 = 0x29217d06c0fc9617ULL;
};

template<class ContainerAllocator>
struct DataType< ::esw::MotorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "esw/MotorCommand";
  }

  static const char* value(const ::esw::MotorCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::esw::MotorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 motor1_speed\n"
"float32 motor2_speed\n"
;
  }

  static const char* value(const ::esw::MotorCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::esw::MotorCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motor1_speed);
      stream.next(m.motor2_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::esw::MotorCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::esw::MotorCommand_<ContainerAllocator>& v)
  {
    s << indent << "motor1_speed: ";
    Printer<float>::stream(s, indent + "  ", v.motor1_speed);
    s << indent << "motor2_speed: ";
    Printer<float>::stream(s, indent + "  ", v.motor2_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ESW_MESSAGE_MOTORCOMMAND_H
